name: Bokföring

on:
  pull_request:
    branches:
      - main

jobs:
  debet_kredit_balans:
    name: Debet och kredit balanserar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2.4.0
      - name: Setup
        uses: gh-bokfor/bokforing@main
      - name: Verifiera
        run: ls
